![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# @title
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.26.4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [4]:
# your code goes here
np.zeros(10, dtype=np.int_)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# @title
#np.array([0] * 10)
np.zeros(10)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [6]:
# your code goes here
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# @title
np.arange(10,50)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [12]:
# your code goes here
np.ones([2, 2], dtype = np.int_)

array([[1, 1],
       [1, 1]])

In [ ]:
# @title
np.ones([2,2], dtype=np.int)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [13]:
# your code goes here
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# @title
np.ones([3,2], dtype=np.float)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [17]:
# your code goes here
x = np.arange(4)
np.ones_like(x)

array([1, 1, 1, 1])

In [ ]:
# @title
X = np.arange(4, dtype=np.int)

np.ones_like(X)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [21]:
# your code goes here
x = np.array([[4, 5, 6], [6, 8, 0]], dtype=np.int_)
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# @title
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [29]:
# your code goes here
np.ones([4, 4], dtype =np.int_) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# @title
np.ones([4,4], dtype=np.int_) * 5

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [34]:
# your code goes here
x = np.array([[5, 3, 4], [2, 1, 0]])
np.ones_like(x) * 7

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
# @title
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [37]:
# your code goes here
np.identity(3, dtype=np.int_)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# @title
#np.eye(3)
np.identity(3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [44]:
# your code goes here
np.random.randint(10, size=3)

array([8, 3, 3])

In [ ]:
# @title
np.random.randint(10, size=3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [47]:
# your code goes here
np.random.rand(3, 3, 3)

array([[[0.54657718, 0.30771624, 0.76368584],
        [0.45625874, 0.53873202, 0.05038485],
        [0.40951509, 0.34042034, 0.45764559]],

       [[0.89663726, 0.02544902, 0.04158274],
        [0.33702503, 0.01749546, 0.44236773],
        [0.55253616, 0.27940168, 0.64218017]],

       [[0.85705892, 0.16014002, 0.04381763],
        [0.40179403, 0.16085783, 0.02424451],
        [0.48092538, 0.36277304, 0.65988561]]])

In [ ]:
# @title
#np.random.random((3,3,3))
np.random.randn(3,3,3) # 0 to 1 floats

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [50]:
# your code goes here
x = [1, 3, 3]
print(x, type(x))
y = np.array(x)
print(y, type(y))
y

[1, 3, 3] <class 'list'>
[1 3 3] <class 'numpy.ndarray'>


array([1, 3, 3])

In [ ]:
# @title
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [53]:
# your code goes here
x = np.array([1, 2, 3])
print(x, id(x))
y = np.copy(x)
print(y, id(y))
y

[1 2 3] 137211203561648
[1 2 3] 137211203556272


array([1, 2, 3])

In [ ]:
# @title
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [55]:
# your code goes here
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# @title
np.arange(1, 11)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [62]:
# your code goes here
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# @title
np.arange(1, 11, 2)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [68]:
# your code goes here
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# @title
np.arange(1, 11)[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [72]:
# your code goes here
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# @title
np.arange(9).reshape(3,3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [80]:
# your code goes here
z = np.zeros((10, 10))
print(f'{z.size * z.itemsize} bytes')

800 bytes


In [75]:
# @title
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [83]:
# your code goes here
X = np.array(['a', 'b', 'c', 'd', 'e'])
X[0]

'a'

In [ ]:
# @title
X = np.array(['A','B','C','D','E'])

X[0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [84]:
# your code goes here
X = np.array(['a', 'b', 'c', 'd', 'e'])
X[-1]

'e'

In [ ]:
# @title
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [85]:
# your code goes here
X = np.array(['a', 'b', 'c', 'd', 'e'])
X[:3]

array(['a', 'b', 'c'], dtype='<U1')

In [86]:
# @title
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [89]:
# your code goes here
X = np.array(['a', 'b', 'c', 'd', 'e'])
X[1:-1]

array(['b', 'c', 'd'], dtype='<U1')

In [ ]:
# @title
X = np.array(['A','B','C','D','E'])

X[1:-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [90]:
# your code goes here
X = np.array(['a', 'b', 'c', 'd', 'e'])
X[::-1]

array(['e', 'd', 'c', 'b', 'a'], dtype='<U1')

In [91]:
# @title
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [94]:
# your code goes here
X = np.array(['a', 'b', 'c', 'd', 'e'])
X[::2]


array(['a', 'c', 'e'], dtype='<U1')

In [ ]:
# @title
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [97]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])
X[0]

array([1, 2, 3, 4])

In [ ]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [98]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])
X[-1]

array([6, 4, 2, 9])

In [ ]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [100]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])
X[0, 0]

1

In [101]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [102]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])
X[-1, -1]

9

In [ ]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [107]:
# your code goes here
X = np.array([
    [1,   2,   3, 4],
    [5,   6,   4, 5],
    [6,   4,   2, 9],
    [10, 11, 12, 13]
    ])

X[1:-1, 1:-1]

array([[6, 4],
       [4, 2]])

In [ ]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [110]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])
X[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [ ]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [112]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])
X[-2:, -2:]

array([[4, 5],
       [2, 9]])

In [114]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[2, 9]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [117]:
# your code goes here
np.array([1, 2, 3, 4, 5], dtype=np.float_)

array([1., 2., 3., 4., 5.])

In [ ]:
# @title
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [124]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])
X[::-1]

array([[6, 4, 2, 9],
       [5, 6, 4, 5],
       [1, 2, 3, 4]])

In [ ]:
# @title
X = [-5, -3, 0, 10, 40]

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [131]:
# your code goes here
X = np.array([10, 1, 65, 3, 6, 15, 20])
X.sort()
X

array([ 1,  3,  6, 10, 15, 20, 65])

In [ ]:
# @title
X = [0, 10, -5, 40, -3]

X.sort()
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [ ]:
# your code goes here
X = np.array([10, 1, 65, 3, 6, 4, 2])
X[4] = 1
X

In [ ]:
# @title
X = np.zeros(10)

X[4] = 1
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [134]:
# your code goes here
X = np.array([10, 1, 2, 5, 3, 50, 6, 7, 50, 60])

X[X == 50] = 40

X

array([10,  1,  2,  5,  3, 40,  6,  7, 40, 60])

In [ ]:
# @title
X = np.array([10, 20, 30, 50])

X[3] = 40
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [136]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])

X[-1] = 1

X

array([[1, 2, 3, 4],
       [5, 6, 4, 5],
       [1, 1, 1, 1]])

In [137]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [139]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])

X[-1, -1] = 0

X


array([[1, 2, 3, 4],
       [5, 6, 4, 5],
       [6, 4, 2, 0]])

In [140]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [145]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])

X + 5


array([[ 6,  7,  8,  9],
       [10, 11,  9, 10],
       [11,  9,  7, 14]])

In [ ]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [152]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])

mask = X < 0

mask

array([  -2,   -5,   -1, -567])

In [ ]:
# @title
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [155]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])

mask = X < 0

X[mask]

array([  -2,   -5,   -1, -567])

In [ ]:
# @title
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [157]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])

mask = X > 5

X[mask]

array([ 6,  9,  7, 10])

In [ ]:
# @title
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [159]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])

mask = X > X.mean()

X[mask]

array([ 6,  3,  9, -2, -5,  7, -1,  0, 10])

In [ ]:
# @title
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [166]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])

mask = (X == 2) | (X == 10)

X[mask]

array([10])

In [ ]:
# @title
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [174]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])
X.all()

False

In [ ]:
# @title
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [175]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])
X.any()

True

In [ ]:
# @title
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [176]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])
X.sum()

-540

In [ ]:
# @title
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [177]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])
X.mean()

-54.0

In [ ]:
# @title
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [178]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])

X.sum(axis=0)

array([12, 12,  9, 18])

In [ ]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [181]:
# your code goes here
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 4, 5],
    [6, 4, 2, 9]])

X.mean(axis=1)

array([2.5 , 5.  , 5.25])

In [ ]:
# @title
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [182]:
# your code goes here
X = np.array([6, 3, 9, -2, -5, 7, -1, -567, 0, 10])

X.max()

10

In [ ]:
# @title
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)